"""
Train the temporal behavior-analysis model.

This script is the training entry point for the behavior-analysis
component of the surveillance system.

Behavior classes:
    standing
    walking
    running
    falling
    fighting
    loitering
    suspicious_object_handling

The project dataset is organized into:
    data/train/
    data/val/
    data/test/

The temporal behavior model is intended to use a SlowFast-based
architecture. Training data must therefore be represented as
sequences of video frames rather than independent images.

The script expects prepared temporal clip manifests generated by:

    scripts/prepare_behavior_dataset.py

Expected manifests:

    data/behavior_prepared/
        train_manifest.json
        val_manifest.json
        test_manifest.json

Training output:

    weights/
        behavior_best.pth

IMPORTANT:
This script defines the training entry point and model-training
pipeline. Actual training metrics must be generated from the
behavior dataset and should not be confused with the existing
YOLO object-detection metrics reported in results/.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Dict, List

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset


BEHAVIOR_CLASSES = [
    "standing",
    "walking",
    "running",
    "falling",
    "fighting",
    "loitering",
    "suspicious_object_handling",
]


class BehaviorClipDataset(Dataset):
    """
    Dataset for temporal behavior clips.

    Each manifest entry contains:

        {
            "clip_id": "...",
            "label": "...",
            "frame_paths": [...]
        }

    Frame loading and SlowFast preprocessing are kept inside
    this dataset so that the training loop remains independent
    of the underlying file structure.
    """

    def __init__(
        self,
        manifest_path: Path,
        class_names: List[str],
    ) -> None:

        self.manifest_path = Path(
            manifest_path
        )

        self.class_names = class_names

        self.class_to_index = {
            name: index
            for index, name in enumerate(
                class_names
            )
        }

        if not self.manifest_path.exists():
            raise FileNotFoundError(
                f"Manifest not found: "
                f"{self.manifest_path}"
            )

        with self.manifest_path.open(
            "r",
            encoding="utf-8",
        ) as file:

            self.samples = json.load(file)

        if not self.samples:
            raise ValueError(
                f"No samples found in "
                f"{self.manifest_path}"
            )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, index: int):

        sample = self.samples[index]

        label_name = sample["label"]

        if label_name not in self.class_to_index:
            raise ValueError(
                f"Unknown behavior class: "
                f"{label_name}"
            )

        frame_paths = sample["frame_paths"]

        frames = self._load_frames(
            frame_paths
        )

        frames = self._preprocess_frames(
            frames
        )

        label = self.class_to_index[
            label_name
        ]

        return (
            frames,
            torch.tensor(
                label,
                dtype=torch.long,
            ),
        )

    @staticmethod
    def _load_frames(
        frame_paths: List[str],
    ) -> List[np.ndarray]:
        """
        Load the image sequence.

        OpenCV is imported here so the dataset can remain
        compatible with the existing surveillance pipeline.
        """

        import cv2

        frames = []

        for frame_path in frame_paths:

            frame = cv2.imread(
                str(frame_path)
            )

            if frame is None:
                raise FileNotFoundError(
                    f"Unable to read frame: "
                    f"{frame_path}"
                )

            frame = cv2.cvtColor(
                frame,
                cv2.COLOR_BGR2RGB,
            )

            frames.append(frame)

        return frames

    @staticmethod
    def _preprocess_frames(
        frames: List[np.ndarray],
    ) -> torch.Tensor:
        """
        Convert frames to a temporal tensor.

        Output layout:

            C x T x H x W

        where:

            C = RGB channels
            T = temporal frames
            H = image height
            W = image width

        SlowFast-specific pathway construction is handled
        separately by the model/training implementation.
        """

        import cv2

        processed = []

        for frame in frames:

            frame = cv2.resize(
                frame,
                (224, 224),
            )

            frame = (
                frame.astype(
                    np.float32
                )
                / 255.0
            )

            processed.append(
                frame
            )

        array = np.stack(
            processed,
            axis=0,
        )

        tensor = torch.from_numpy(
            array
        )

        tensor = tensor.permute(
            3,
            0,
            1,
            2,
        )

        return tensor


class SlowFastBehaviorModel(nn.Module):
    """
    SlowFast behavior model interface.

    This class is intentionally structured as the model boundary
    for the project. The exact SlowFast backbone/checkpoint
    configuration must match the behavior-training setup.

    It should not be confused with the YOLOv8 object detector.
    """

    def __init__(
        self,
        num_classes: int,
    ) -> None:

        super().__init__()

        self.num_classes = num_classes

        # The final project implementation should instantiate
        # the selected SlowFast backbone here and replace its
        # classification head with `num_classes` outputs.

        self.model = None

    def forward(
        self,
        x,
    ):

        if self.model is None:

            raise NotImplementedError(
                "SlowFast backbone has not been "
                "configured yet. Configure the "
                "project SlowFast implementation "
                "before training."
            )

        return self.model(x)


def parse_args() -> argparse.Namespace:
    """Parse command-line training arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Train the SlowFast behavior-analysis model."
        )
    )

    parser.add_argument(
        "--train-manifest",
        type=Path,
        default=Path(
            "data/behavior_prepared/"
            "train_manifest.json"
        ),
    )

    parser.add_argument(
        "--val-manifest",
        type=Path,
        default=Path(
            "data/behavior_prepared/"
            "val_manifest.json"
        ),
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "weights/behavior_best.pth"
        ),
    )

    parser.add_argument(
        "--epochs",
        type=int,
        default=50,
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
    )

    parser.add_argument(
        "--learning-rate",
        type=float,
        default=1e-4,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
    )

    return parser.parse_args()


def set_seed(seed: int) -> None:
    """Set deterministic random seeds."""

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def create_dataloaders(
    train_manifest: Path,
    val_manifest: Path,
    batch_size: int,
):

    train_dataset = BehaviorClipDataset(
        manifest_path=train_manifest,
        class_names=BEHAVIOR_CLASSES,
    )

    val_dataset = BehaviorClipDataset(
        manifest_path=val_manifest,
        class_names=BEHAVIOR_CLASSES,
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
    )

    return (
        train_loader,
        val_loader,
    )


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> float:

    model.train()

    running_loss = 0.0

    for inputs, labels in loader:

        inputs = inputs.to(
            device
        )

        labels = labels.to(
            device
        )

        optimizer.zero_grad()

        outputs = model(inputs)

        loss = criterion(
            outputs,
            labels,
        )

        loss.backward()

        optimizer.step()

        running_loss += (
            loss.item()
            * inputs.size(0)
        )

    return (
        running_loss
        / len(loader.dataset)
    )


@torch.no_grad()
def evaluate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
):

    model.eval()

    running_loss = 0.0

    correct = 0

    total = 0

    for inputs, labels in loader:

        inputs = inputs.to(
            device
        )

        labels = labels.to(
            device
        )

        outputs = model(inputs)

        loss = criterion(
            outputs,
            labels,
        )

        running_loss += (
            loss.item()
            * inputs.size(0)
        )

        predictions = (
            outputs.argmax(dim=1)
        )

        correct += (
            predictions == labels
        ).sum().item()

        total += labels.size(0)

    average_loss = (
        running_loss
        / len(loader.dataset)
    )

    accuracy = (
        correct / total
        if total > 0
        else 0.0
    )

    return (
        average_loss,
        accuracy,
    )


def save_checkpoint(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    epoch: int,
    validation_accuracy: float,
    output_path: Path,
) -> None:

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    torch.save(
        {
            "epoch": epoch,
            "model_state_dict": (
                model.state_dict()
            ),
            "optimizer_state_dict": (
                optimizer.state_dict()
            ),
            "validation_accuracy": (
                validation_accuracy
            ),
            "classes": BEHAVIOR_CLASSES,
        },
        output_path,
    )


def main() -> None:

    args = parse_args()

    set_seed(
        args.seed
    )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print(
        f"[INFO] Device: {device}"
    )

    print(
        "[INFO] Behavior classes:"
    )

    for index, class_name in enumerate(
        BEHAVIOR_CLASSES
    ):
        print(
            f"  {index}: {class_name}"
        )

    train_loader, val_loader = (
        create_dataloaders(
            train_manifest=args.train_manifest,
            val_manifest=args.val_manifest,
            batch_size=args.batch_size,
        )
    )

    model = SlowFastBehaviorModel(
        num_classes=len(
            BEHAVIOR_CLASSES
        )
    ).to(device)

    criterion = nn.CrossEntropyLoss()

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
    )

    best_accuracy = 0.0

    for epoch in range(
        args.epochs
    ):

        train_loss = train_one_epoch(
            model=model,
            loader=train_loader,
            criterion=criterion,
            optimizer=optimizer,
            device=device,
        )

        validation_loss, validation_accuracy = (
            evaluate(
                model=model,
                loader=val_loader,
                criterion=criterion,
                device=device,
            )
        )

        print(
            f"Epoch "
            f"{epoch + 1}/{args.epochs} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {validation_loss:.4f} | "
            f"Val Accuracy: "
            f"{validation_accuracy:.4f}"
        )

        if validation_accuracy > best_accuracy:

            best_accuracy = (
                validation_accuracy
            )

            save_checkpoint(
                model=model,
                optimizer=optimizer,
                epoch=epoch + 1,
                validation_accuracy=(
                    validation_accuracy
                ),
                output_path=args.output,
            )

            print(
                f"[INFO] Saved best checkpoint: "
                f"{args.output}"
            )


if __name__ == "__main__":
    main()
